# Generated by Django 4.2.11 on 2024-09-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
