# Generated by Django 4.2.11 on 2024-09-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_job_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="job",
            name="published_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="vacany",
            field=models.IntegerField(default=1),
        ),
    ]
