# Generated by Django 4.2.11 on 2024-09-03 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0004_category_alter_job_experience_alter_job_salary_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="vacany",
            new_name="vacancy",
        ),
    ]
