# Generated by Django 4.2.11 on 2024-09-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0005_rename_vacany_job_vacancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.ImageField(default="", upload_to="jobs/"),
            preserve_default=False,
        ),
    ]
